### PR TITLE
Use unique titles for each page

### PR DESCRIPTION
**Pull request by ryanolsonx**
Adds titles (and subtitles) to each of the pages.  For example, Legal would be "Legal - Ember.js" and LTS releases would be "LTS - Releases - Ember.js".

I preserved the title for the home page "Ember.js - A framework for ambitious web developers".

See: #313

Side note: some Ember.js websites outside of this project use "Ember.js - Foo" while this PR uses "Foo - Ember.js".  We may need to change the naming pattern in the other places OR here.

### CODE REVIEW

**Comment by ryanolsonx** [comment]
I know there's a major redesign happening currently, but I think this can still be of value for the current site. @wifelette @mansona

**Comment by mansona** [comment]
@ryanolsonx don't worry too much about the redesign, if we get this merged into master then we will make sure that we either do a rebase or a merge into the new branch so it doesn't get lost 👍 

I have 2 concerns about this PR though 🤔 firstly looking at the titles they are all very "functional", and this is the reason why in the main issue I asked if the new SEO team would be looking at it (I'm not sure if this team ever got together in the end). The issue being is that the title is a very strong indication to the SEO, and we should be thinking about putting things in there that are what we want people to find Ember for search terms.

For example the new title for https://emberjs.com/releases/release/  is `Stable - Releases - Ember.js. Maybe that's what we actually want if we expect people to search for something like "Ember Stable" 🤔 but I'm wondering if there can be more thought put into it.

On the other side of this, considering this from a technical perspective instead of the content of each of the titles, I'm not sure if I want us to use ember-page-title for this 🤔 we have been using https://github.com/shipshapecode/ember-meta for other Ember sites which has allowed us to update things other than the title, including the Open Graph tags like `<meta property="st:title"`. The only issue is that it is more route and model based but not all of our routes have models 🤔 @rwwagner90 do you have any insights on how we might use ember-meta without routes or models? 

The reason why I would be interested in looking at ember-meta is that in this PR the `<title>` tag does not match the Open Graph metadata: 

```html
<meta property="st:title" content="Ember.js: A framework for ambitious web developers" />
<title>Stable - Releases - Ember.js</title>
```

Sorry if this is a bit of a brain dump but I've been thinking about your PR for a long time since you submitted it 😂

**Comment by rwwagner90** [comment]
@mansona I added a `this.metaInfo` option to ember-meta, so you can set the meta separately from the model. I believe that should work for our use case.

**Comment by ryanolsonx** [comment]
@mansona Thanks for the thorough insights on this PR.  I'll wait until the new SEO team gives their thoughts.  Once they respond, I can refactor this to ember-meta.

👍

**Comment by rwwagner90** [comment]
@mansona is there an SEO team?

I think the general titles proposed here are good. Most sites do `Specific To Page - Website Name` formatted titles.

**Comment by ryanolsonx** [comment]
@rwwagner90 Most of the titles should be in "Specific to Page - Website Name" format.  There are a few that are subpages which would get "Sub Page - Parent Page - Website Name".  This could change to a simple "Specific to Page - Website Name" everywhere.

In the example given above, "Stable - Releases - Ember.js" can become "Stable Release - Ember.js" or something.

**Comment by rwwagner90** [comment]
@ryanolsonx I don't think changing is necessary. `Child - Parent - Website` is pretty typical. I think this would really help our SEO a ton. I am in favor 👍

**Comment by ryanolsonx** [comment]
> `Child - Parent - Website` is pretty typical. I think this would really help our SEO a ton.

Not only would it help SEO, but it would help if a user bookmarks the page to have something that gives context.

**Pull request merged**
