### PR TITLE
Fix mascots

### PR DESCRIPTION
**Pull request by mansona**
This was an attempt to fix the mascots page using just the css helpers available in the styleguide. As you can see from the inclusion of some CSS it didn't quite hit that goal 😞 

We should discuss ways to make this less necessary or if we will, in fact, need some custom CSS for this page

https://deploy-preview-375--ember-website.netlify.com/mascots/

mascots

### CODE REVIEW

**Comment by mansona** [comment]
I have used the latest style guide and we are now able to use significantly less CSS in this PR but we still have a little way to go 👍

**Comment by MelSumner** [comment]
Let's talk about this in the website team meeting- this is exactly one of the use cases for the list component.

**Comment by mansona** [comment]
@ghislaineguerin I'm going to assign this to you. We have discussed the need for more flexibility with the card "component" i.e. card image, card detail etc.

Ideally we should be able to implement this page without the need for custom CSS in the website page. Let me know if you have any questions! 😂

**Comment by mansona** [comment]
This PR is now ready to be reviewed and merged 🎉 

deploy-preview-375--ember-website netlify com_mascots_ (1)

I have avoided the need for "page CSS" by moving the `<TomsterList />` into a component.

**Pull request merged**
