### PR TITLE
Update browser-support

### PR DESCRIPTION
**Pull request by jaredgalanis**

### CODE REVIEW

**Comment by jaredgalanis** [comment]
not stale

**Comment by chriskrycho** [comment]
@jaredgalanis @locks this is a great and much-needed update—can we get it finished up and pushed across the line? 🤩

**Comment by chriskrycho** [comment]
@locks and I talked about this via DM a bit and we don’t have a *perfectly* clear idea what the right move here should be. I *suspect* that instead of listing specific versions for the evergreen browsers, we should just say the policy there, and list specific versions for the browsers which *do* have specific versions (read: Safari).

**Review by mansona — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
