### PR TITLE
Rename Lendix to October

### PR DESCRIPTION
**Pull request by tcouloumy**
Lendix changed identity to become October a little while ago, but we still use Ember !
Here's a little PR to update Ember's website user page to reflect that

### CODE REVIEW

**Comment by amyrlam** [comment]
@tcouloumy thanks! Would you mind filling out https://airtable.com/shrZSLswT03VpzY1D?

**Comment by ijlee2** [comment]
Hi, @amyrlam. I approved the Percy change (a style diff unrelated to the PR). I'll let you merge the pull request once you receive the form submission.

**Comment by tcouloumy** [comment]
@amyrlam Form filled and submitted :)

**Review by amyrlam — APPROVED** [review]
thank you both!

**Pull request merged**
