### PR TITLE
Fix ember engines guides link

### PR DESCRIPTION
**Pull request by villander**
cc: @locks

### CODE REVIEW

**Comment by mansona** [comment]
we really should make sure that the old link works so that we don't drop SEO or break any links 🤔 what method of redirects do you have available in the place that it's currently hosted?

**Comment by villander** [comment]
It already implemented on Engines Guides @mansona 

https://github.com/ember-engines/ember-engines.com/blob/master/tests/dummy/app/routes/guide.js

**Comment by mansona** [comment]
@villander so that's not a "SEO redirect". That won't allow links that are giving any sort of domain authority to apply it to the app any more. I will make sure that I create an issue that covers the problem or maybe we can bring it up in the learning team meeting 👍

**Comment by villander** [comment]
@mansona it was required by @locks to fix SEO. Now I'm not sure what's right.

**Pull request merged**
