### PR TITLE
Make ember the together framework

### PR DESCRIPTION
**Pull request by gossi**
Because !

### CODE REVIEW

**Comment by gossi** [comment]
I love the change @MelSumner - sounds really great. I don't know what the label `steering` means in this context, but is this the way forward for this ticket?

**Comment by mansona** [comment]
@gossi because this is such a prominent change to the "tagline" of Ember it likely needs to be discussed at the steering committee meeting 👍 (which happens on a Friday)

**Comment by gossi** [comment]
@mansona I expected that, thanks for the explanation - much appreciated and also to consider it 👍

**Comment by MelSumner** [comment]
This is a great idea! We've discussed it in Steering Committee, and decided that we're going to close this PR while we work through the wording some more- there's some more conversations that we need to have about the shift before we change the website. Stay tuned! 👍

**Pull request closed without merging**
