### PR TITLE
Add /logos/ route new sections and anchor links

### PR DESCRIPTION
**Pull request by samridhivig**
This MR works on the Copy/Content Updates to /logos/ page #1007 issue tasks:

1. Each section has an ID that can be used in the anchor link in order to navigate to a specific section
2. Added id to each Mascot ListItem li i.e `mascot.id`
3. Added the necessary sections
4. Added links to each instance of the Standard Art Set
5. Added the links to the mascot items specified in Standard Art Set

### CODE REVIEW

**Review by mansona — CHANGES_REQUESTED** [review]
Thanks for the contribution 🎉 can you just remove the yarn.lock and we can get this merged? we're just using npm on this project so we don't have a yarn.lock file here 👍

**Comment by wifelette** [comment]
It looks like the anchors on the Mascots aren't working. If you follow the new links on the Brand page, the URL is updating, but the mascots page jumps back to the top. Just me?

This looks otherwise amazing, thank you @samridhivig so much for doing the work, and sorry I've been offline and haven't said that sooner!

**Comment by MinThaMie** [comment]
Same here, in the preview and running it locally ;) So theoretically this should work but the router inserts a `/` between the page and the section so that's why it jumps to the beginning. I'll check at the learning meeting if somebody there knows why.

**Comment by mansona** [comment]
So this came up a long time ago when I tried to implement the same thing. The issue is that we need to enable an experimental feature on Fastboot that will allow this to work as expected 🙈 (It's EXPERIMENTAL_RENDER_MODE_SERIALIZE for reference)

We discussed this in the Learning team today and we think it's probably best to update this PR to not include the links to the specific Tomsters/Zoes and we can fix the linking problem in a different PR. Essentially we're not 100% comfortable enabling the experimental feature without testing it and we didn't want to block the other important bits of this PR.

What do you think?

**Comment by mansona** [comment]
It turns out we figured out how to make the links work with #1120 so I've rebased this and if the links are working on the demo site I'll get it merged 👍

**Review by mansona — APPROVED** [review]

**Pull request merged**
