### PR TITLE
Convert the Security page https://emberjs.com/security/ 

### PR DESCRIPTION
**Pull request by aklkv**
fixes: #18

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
Thanks for the multiple PRs @aklkv🙌. Could you please use commit messages that describe the changes made in it & have the PR titles mention the same as well? That'd make it easy for both the reviewers & well as looking through git history later.

**Comment by aklkv** [comment]
@sivakumar-kailasam Oh. Sorry about that, I thought you guys just do squish merge anyway. I will make sure I make it more descriptive for next once

**Comment by sivakumar-kailasam** [comment]
No worries. We avoid squish commits since it drops the info on the original author & we'd like to keep our contributions intact 🙂

**Comment by sivakumar-kailasam** [comment]
@aklkv this seems to be updating the security page & not the sponsors page. Could you please update the PR?

**Comment by aklkv** [comment]
@sivakumar-kailasam done

**Comment by mansona** [comment]
this was fixed by #74 👍

**Pull request closed without merging**
