### PR TITLE
Update {release,beta}.md for latest release of ember & ember-data

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**

### CODE REVIEW

**Comment by mansona** [comment]
I have approved because it looks good, but I would recommend holding off merging until the Blog Post is published. Just a thought, it's not up to me to decide 😂

**Comment by sivakumar-kailasam** [comment]
@kategengler requested this on discord. I’ll leave it to her to merge this when she thinks it’s good to go 🙂

**Comment by kategengler** [comment]
Thanks @sivakumar-kailasam! 

@mansona I personally don't think waiting for the blog post is necessary. After all, anybody doing `npm install ember-source` is going to get the new version.

**Comment by mansona** [comment]
@kategengler thanks for the insight 👍 I'll try to remember this for next time 😂

**Pull request merged**
