### PR TITLE
Add BoondManager to users

### PR DESCRIPTION
**Pull request by mpirio**
Hello,

Added BoondManager to users. Thanks!

Regards,

### CODE REVIEW

**Comment by amyrlam** [comment]
Not sure why `Ember Asset Sizes` failed, but merging

**Comment by mpirio** [comment]
Thank you

**Comment by mpirio** [comment]
Hello @amyrlam ,

Our graphic designer has just informed me that we had flattened our logo when we created the PNG image. Is it possible to send you again the new PNG image in this PR or do I have to open another PR?

Thank you.

**Comment by amyrlam** [comment]
@mpirio ah gotcha - please open another branch / PR and tag me in it!

**Pull request merged**
