### PR TITLE
Close navbar dropdown after router transition

### PR DESCRIPTION
**Pull request by patocallaghan**
Fixes https://github.com/ember-learn/ember-website/issues/151

After each router transition we use the `navbar` service to close dropdown menu. This bumps `ember-styleguide` to bring the `navbar#closePopupMenu` method introduced in https://github.com/ember-learn/ember-styleguide/pull/142

navbar

### CODE REVIEW

**Comment by patocallaghan** [comment]
So it likes CI is failing potentially due to a caching issue. It looks like Travis is using an older version without the `closePopupMenu`. Any ideas @mansona?

**Comment by mansona** [comment]
@patocallaghan I think it's just Yarn being difficult 🙈 it should be using the right one because of the yarn.lock file.

I'll take a look

**Comment by patocallaghan** [comment]
Yeah, the commit SHA for ember-styleguide is correct for current master 🤷‍♂️

**Comment by patocallaghan** [comment]
@mansona I've updated to use the commit SHA in the package.json. Will see if that works

**Comment by patocallaghan** [comment]
Thanks @mansona, I think once we get a new release version of ember-styleguide we can go back to Yarn. The README will probably need updating too as it currently references `yarn`.

**Pull request merged**
