### PR TITLE
[WIP] Ember Website Redesign initial spike

### PR DESCRIPTION
**Pull request by mansona**
This is an initial spike of the Website Redesign

### CODE REVIEW

**Comment by MelSumner** [comment]
Closing this branch based on a change in direction.

**Comment by MelSumner** [comment]
(Reoopened it after realizing I closed the wrong one, oops!)

**Comment by MelSumner** [comment]
leave it open please.

**Comment by mansona** [comment]
I'm closing this in favour of #361 because it caused a bit of confusion with contributors 🙈 the branch is still here named `initial-spike` so no work is lost 👍

**Comment by andrewjosephderocher** [comment]
Wow

**Pull request closed without merging**
