### PR TITLE
New user Beijer Electronics added.

### PR DESCRIPTION
**Pull request by GottfridL**
Added new user Beijer Electronics.

### CODE REVIEW

**Comment by MinThaMie** [comment]
Apparently your SSL certificate is not okay. I don't think we'll merge before that!

Screenshot 2022-09-27 at 13 38 07

**Comment by GottfridL** [comment]
It should be ok now. Thanks for pointing that out.Kind regardsGottfrid Linge Den 27 sep. 2022 13:39 skrev Anne-Greeth Schot-van Herwijnen ***@***.***>:
Apparently your SSL certificate is not okay. I don't think we'll merge before that!

**Review by MinThaMie — APPROVED** [review]
Looks good now :) Welcome to the club!

**Comment by NullVoxPopuli** [comment]
Did the issue return? 
image

**Pull request merged**
